FROM node:alpine3.18 AS build

WORKDIR /app

COPY ./src/package*.json ./

RUN npm install

COPY ./src/ ./

RUN npm run build 


FROM nginx:alpine3.18
WORKDIR /usr/share/nginx/html
COPY --from=build /app/public .


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]