version: '3'

networks:
  arnab:
    external: true

services:
  notificationdb-mongo-express:
    image: mongo-express
    container_name: notificationdb-mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@notificationdb:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    depends_on:
      - notificationdb
    restart: unless-stopped
    # ports:
    #   - "8085:8081"  
    networks:
      arnab:
        ipv4_address: 172.20.0.65
  notificationdb:
    image: mongo:5.0
    container_name: notificationdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    # ports:
    #   - "27020:27017"
    volumes:
      - ./database/mongodb/db:/data/db
      - ./database/mongodb/dev.archive:/Databases/dev.archive
      - ./database/mongodb/production:/Databases/production
    command: [ "--auth" ]
    networks:
      arnab:
        ipv4_address: 172.20.0.75